import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from "./nopage/components/navbar"
import Footer from './nopage/components/footer'
import Headline from "./nopage/components/headline"
import Bottom from "./nopage/components/bottom"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Erroneous Gold',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-back'>
      <body className={inter.className}>
        <div className=" fo">
          <Headline/>
        <Navbar/>
        {children}
        <Bottom/>
        <Footer/>
        </div>
        </body>
    </html>
  )
}
