import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from "./nopage/components/navbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Erroneous Gold',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-back'>
      <body className={inter.className}>
        <div className="px-2 ">
        <Navbar/>
        {children}
        </div>
        </body>
    </html>
  )
}
